### ISSUE TITLE
where should the file to put for Emacs Version 25.2 (9.0)

### ISSUE THREAD

**Issue by jack2gs** [thomas-villagers/ob-csharp#1]
Hi, 

I'm trying to use ob-csharp. But I don't know where to put it. Could you tell me please?
OS: macOS 10.12.5 (16F73)
Emacs:  Version 25.2 (9.0)

Cheers,
Jack

**Comment by thomas-villagers** [comment]
Hi Jack,

put it in your org-install folder where the other ob-files exist (ob-C, 
ob-calc, ob-ruby etc.), i. e. ~/.emacs/elpa/org-XXXXXX/

that should do it ... can you find the ob-files on your system?


- thomas

**Comment by jack2gs** [comment]
Hi Thomas,

I got it run.  I use Emacs.app on macOS. So it's a little different with your instruction. Org-mode is at Emacs.app/Content/Resources/lisp/org. And I gzip it first. Then put the ob-csharp.el.gz to that directory.

Cheers,
Jack
